"use client";

import { useCallback, useEffect, useState } from "react";
import { Star } from "lucide-react";
import { Alert, Button, Label } from "@/components/ui";
import { ApiRequestError } from "@/lib/api";
import type { Order } from "@/lib/orders";
import { createItemReview, createSellerReview, getReviewEligibility, type ReviewEligibility } from "@/lib/reviews";

const words = (value: string) => value.trim().split(/\s+/u).filter(Boolean).length;

function RatingInput({ name }: { name: string }) {
  return <div className="flex gap-2" role="radiogroup" aria-label="Rating from 1 to 5 stars">{[1, 2, 3, 4, 5].map((rating) => <label key={rating} className="cursor-pointer"><input className="peer sr-only" type="radio" name={name} value={rating} required /><span className="flex h-10 w-10 items-center justify-center rounded-full border border-line text-muted peer-checked:border-primary peer-checked:bg-primary-soft peer-checked:text-primary"><Star className="h-5 w-5 fill-current" /><span className="sr-only">{rating} stars</span></span></label>)}</div>;
}

export function OrderReviewSection({ order }: { order: Order }) {
  const [data, setData] = useState<ReviewEligibility | null>(null); const [busy, setBusy] = useState<string | null>(null); const [error, setError] = useState<string | null>(null); const [notice, setNotice] = useState<string | null>(null);
  const [itemText, setItemText] = useState<Record<string, string>>({}); const [sellerText, setSellerText] = useState("");
  const [selectedTags, setSelectedTags] = useState<string[]>([]);
  const load = useCallback(() => getReviewEligibility(order._id).then(setData).catch((err) => setError(err instanceof ApiRequestError ? err.message : "Could not load review status.")), [order._id]);
  useEffect(() => { void load(); }, [load]);
  async function submitItem(event: React.FormEvent<HTMLFormElement>, productId: string) { event.preventDefault(); const form = new FormData(event.currentTarget); setBusy(productId); setError(null); try { const result = await createItemReview(order._id, productId, Number(form.get("rating")), itemText[productId] ?? ""); setNotice(result.message); await load(); } catch (err) { setError(err instanceof ApiRequestError ? err.message : "Could not publish review."); } finally { setBusy(null); } }
  async function submitSeller(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); setBusy("seller"); setError(null); try { const result = await createSellerReview(order._id, Number(form.get("rating")), selectedTags, sellerText); setNotice(result.message); await load(); } catch (err) { setError(err instanceof ApiRequestError ? err.message : "Could not publish seller rating."); } finally { setBusy(null); } }
  if (!data?.eligible) return null;
  return <section className="mt-4 rounded-2xl border border-line bg-surface p-5 shadow-soft"><h2 className="font-semibold text-ink">Reviews and ratings</h2><p className="mt-1 text-sm text-muted">Rate the items separately from your experience with the seller.</p>{error && <div className="mt-3"><Alert kind="error">{error}</Alert></div>}{notice && <div className="mt-3"><Alert kind="success">{notice}</Alert></div>}
    <div className="mt-5 space-y-5">{order.items.map((item) => data.itemReviews.some((review) => review.product === item.product) ? <div key={item.product} className="rounded-xl bg-sunken p-4 text-sm text-success">Your review for {item.title} has been published.</div> : <form key={item.product} onSubmit={(event) => void submitItem(event, item.product)} className="rounded-xl border border-line p-4"><h3 className="font-semibold text-ink">Rate {item.title}</h3><div className="mt-3"><RatingInput name="rating" /></div><div className="mt-3"><Label htmlFor={`item-${item.product}`}>Item review (minimum 100 words)</Label><textarea id={`item-${item.product}`} value={itemText[item.product] ?? ""} onChange={(event) => setItemText((current) => ({ ...current, [item.product]: event.target.value }))} required rows={6} className="w-full rounded-xl border border-line px-4 py-3 text-sm" /><p className={`mt-1 text-xs ${words(itemText[item.product] ?? "") >= 100 ? "text-success" : "text-muted"}`}>{words(itemText[item.product] ?? "")} / 100 minimum words</p></div><Button type="submit" loading={busy === item.product} disabled={busy !== null || words(itemText[item.product] ?? "") < 100}>Publish item review</Button></form>)}</div>
    {!data.sellerReview ? <form onSubmit={(event) => void submitSeller(event)} className="mt-5 rounded-xl border border-line p-4"><h3 className="font-semibold text-ink">Rate the seller</h3><div className="mt-3"><RatingInput name="rating" /></div><fieldset className="mt-3"><legend className="text-sm font-medium text-ink">Select 1 to 5 adjectives</legend><div className="mt-2 flex flex-wrap gap-2">{data.tags.map((tag) => <label key={tag} className="cursor-pointer rounded-full border border-line px-3 py-2 text-xs capitalize has-[:checked]:border-primary has-[:checked]:bg-primary-soft has-[:checked]:text-primary"><input type="checkbox" name="tags" value={tag} checked={selectedTags.includes(tag)} disabled={!selectedTags.includes(tag) && selectedTags.length >= 5} onChange={(event) => setSelectedTags((current) => event.target.checked ? [...current, tag] : current.filter((value) => value !== tag))} className="sr-only" />{tag}</label>)}</div></fieldset><div className="mt-3"><Label htmlFor="seller-review">Seller comments (optional, maximum 100 words)</Label><textarea id="seller-review" value={sellerText} onChange={(event) => setSellerText(event.target.value)} rows={4} className="w-full rounded-xl border border-line px-4 py-3 text-sm" /><p className={`mt-1 text-xs ${words(sellerText) > 100 ? "text-danger" : "text-muted"}`}>{words(sellerText)} / 100 words</p></div><Button type="submit" loading={busy === "seller"} disabled={busy !== null || selectedTags.length === 0 || words(sellerText) > 100}>Publish seller rating</Button></form> : <div className="mt-5 rounded-xl bg-sunken p-4 text-sm text-success">Your seller rating has been published.</div>}
  </section>;
}
